POST http://{{host}}:{{port}}/api/items/76/comments
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"text": "Lv1 댓글-{{$timestamp}}"
}

> {%
var status = 201;
client.test("/api/items/76/comments Item(1) Comment 등록 - 로그인필수", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 아이탬에 comment 생성(Lv1 댓글달기)

POST http://{{host}}:{{port}}/api/items/76/comments
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"text": "Lv2 댓글-{{$timestamp}}",
	"parentCommentId": 1
}

> {%
var status = 201;
client.test("/api/items/76/comments Item(1) Comment 등록 - 로그인필수", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 아이탬의 댓글의 하위 comment 생성(Lv2 댓글달기)

GET http://{{host}}:{{port}}/api/items/76/comments
Accept: application/json

> {%
var status = 200;
client.test("/api/items/76/comments Comment 목록 조회", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 아이탬 의 모든 Comment 목록조회

GET http://{{host}}:{{port}}/api/items/76/comments/1
Accept: application/json

> {%
var status = 200;
client.test("/api/items/76/comments/1 - 개별 Comment 조회", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 아이탬 의 id:1 댓글 조회

PATCH http://{{host}}:{{port}}/api/items/76/comments/1
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"text": "Updated 댓글-{{$timestamp}}",
	"parentCommentId": 1
}

> {%
var status = 202;
client.test("/api/items/76/comments - 업데이트", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### comment 업데이트 성공

DELETE http://{{host}}:{{port}}/api/items/76/comments/{{$randomInt}}
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

> {%
var status = 204;
client.test("/api/items/76/comments - 랜덤아이디 삭제시도(성공/실패)", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### comment 랜덤아이디 삭제시도(성공/실패)

POST http://{{host}}:{{port}}/api/items/76/comments/1/likes
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

> {%
var status = 202;
client.test("/api/items/76/comments/1/likes 1번 comment like(맘에듬) 처리 - 로그인필수", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 1번 comment like 처리

DELETE http://{{host}}:{{port}}/api/items/76/comments/1/likes
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

> {%
var status = 202;
client.test("/api/items/76/comments/1/likes 1번 comment unlike(맘에안듬) 처리 - 로그인필수", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 1번 comment unlike 처리
