POST http://{{host}}:{{port}}/api/items
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"link": "https://youtu.be/C6KXeAE4fq0?t=2408",
	"title": "리스팅 기능 구현",
	"body": "벨로퍼트 강의영상",
	"tags": "tag=tag1&tag=tag2&tag=tag3"
}

> {%
var status = 201;
client.test("/api/items Item 등록 - 로그인필수", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### item 생성

GET http://{{host}}:{{port}}/api/items
Accept: application/json

> {%
var status = 200;
client.test("/api/items 아이탬목록 최대 20(limit)개 조회", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### item 아이탬목록 최대 20(limit)개 조회

GET http://{{host}}:{{port}}/api/items?cursor=11
Accept: application/json

> {%
var status = 200;
client.test("/api/items 11번 아이탬부터 최대 20(limit)개 조회", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### item 아이탬목록 최대 20(limit)개 조회

GET http://{{host}}:{{port}}/api/items/1
Accept: application/json

> {%
var status = 200;
client.test("/api/items/1 - 개별 아이탬 조회", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 특정 item 조회성공

GET http://{{host}}:{{port}}/api/items/999999
Accept: application/json

> {%
var status = 404;
client.test("/api/items/9999 - 아이탬 조회실패", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 특정 item 조회실패

PATCH http://{{host}}:{{port}}/api/items/1
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"title":  "updated_title",
	"body": "updated_body",
	"tags": [
      "tag1",
      "tag2"
    ]
}

> {%
var status = 202;
client.test("/api/items - 업데이트", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### item 업데이트 성공

PATCH http://{{host}}:{{port}}/api/items/2
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"title":  "updated_title",
	"body": "updated_body"
}

> {%
var status = 404;
client.test("/api/items - 업데이트실패(필수요소누락)", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### item 업데이트 요소누락실패

PATCH http://{{host}}:{{port}}/api/items/9999
Content-Type: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

{
	"title":  "updated_title",
	"body": "updated_body",
	"tags": [
		"tag1",
		"tag2"
	]
}

> {%
var status = 404;
client.test("/api/items - 없는 item 업데이트불가", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### 없는 item 업데이트 실패

DELETE http://{{host}}:{{port}}/api/items/{{$randomInt}}
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

> {%
var status = 204;
client.test("/api/items - 랜덤아이디 삭제시도(성공/실패)", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " | actual (" + response.status + ")")
})
%}

### item 랜덤아이디 삭제시도(성공/실패)
