GET http://{{host}}:{{port}}/api/me
Accept: application/json
Authorization: Bearer {{access_token}}

> {%
var status = 200;
client.test("/api/me 해더토큰 접근", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " - actual (" + response.status + ")")
})
%}

### 해더 토큰 접근성공

GET http://{{host}}:{{port}}/api/me
Accept: application/json
Cookie: access_token={{access_token}}; refresh_token={{refresh_token}};

> {%
var status = 200;
client.test("/api/me 쿠키토큰 접근", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " - actual (" + response.status + ")")
})
%}

### 쿠키 토큰 접근성공

GET http://{{host}}:{{port}}/api/me
Accept: application/json

> {%
var status = 401;
client.test("/api/me 일반접근", function() {
  client.log("\n");
  client.log("response.body:\t" + JSON.stringify(response.body))
  client.log("\n");

  client.log("client.global 속성목록\n");
  client.log("✔ global::user.id:\t" + client.global.get("user.id"));
  client.log("✔ global::user.username:\t" + client.global.get("user.username"));
  client.log("✔ global::access_token:\t" + client.global.get("access_token"));
  client.log("✔ global::refresh_token:\t" + client.global.get("refresh_token"));

  client.assert(response.status === status, "expected status : " + status + " - actual (" + response.status + ")")
})
%}

### 일반접근